# Generated by Django 5.2.5 on 2025-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="extraction_model",
            field=models.CharField(
                blank=True,
                help_text="The model used to extract the entity.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="extraction_model",
            field=models.CharField(
                blank=True,
                help_text="The model used to extract the relationship.",
                max_length=255,
                null=True,
            ),
        ),
    ]
