# Generated by Django 5.2.5 on 2025-11-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_chunk_block_type"),
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="label",
        ),
        migrations.RemoveField(
            model_name="node",
            name="entity",
        ),
        migrations.RenameField(
            model_name="relationship",
            old_name="relationship_type",
            new_name="relationship",
        ),
        migrations.RemoveField(
            model_name="node",
            name="chunk",
        ),
        migrations.RemoveField(
            model_name="node",
            name="chunk_index",
        ),
        migrations.RemoveField(
            model_name="node",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="node",
            name="extraction_model",
        ),
        migrations.RemoveField(
            model_name="node",
            name="label",
        ),
        migrations.RemoveField(
            model_name="node",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="extraction_model",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="NodeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="The character index of the entity in the chunk."
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.chunk"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="graph.node"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="node",
            name="chunks",
            field=models.ManyToManyField(
                related_name="nodes", through="graph.NodeChunk", to="api.chunk"
            ),
        ),
        migrations.DeleteModel(
            name="Label",
        ),
        migrations.DeleteModel(
            name="Entity",
        ),
    ]
