# Generated by Django 5.2.5 on 2025-11-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_chunk_entities_parse_failed_at_and_more"),
        ("graph", "0002_entity_extraction_model_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entity",
            new_name="Node",
        ),
    ]
