# Generated by Django 5.2.5 on 2025-11-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0002_remove_entity_label_remove_node_entity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodechunk",
            name="chunk_index",
        ),
    ]
