# Generated by Django 5.2.5 on 2025-11-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0003_remove_nodechunk_chunk_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="weight",
            field=models.IntegerField(default=1),
        ),
    ]
