# Generated by Django 5.2.5 on 2025-11-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0003_rename_entity_node"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relationship",
            old_name="left_entity",
            new_name="left_node",
        ),
        migrations.RenameField(
            model_name="relationship",
            old_name="right_entity",
            new_name="right_node",
        ),
    ]
