# Generated by Django 5.2.5 on 2025-11-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0004_relationship_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="relationship",
            field=models.CharField(max_length=1024),
        ),
    ]
