# Generated by Django 5.2.5 on 2025-11-02 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0004_rename_left_entity_relationship_left_node_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="left_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="left_node",
                to="graph.node",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="right_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="right_node",
                to="graph.node",
            ),
        ),
    ]
