# Generated by Django 5.2.5 on 2025-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0005_alter_node_name_alter_relationship_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.CharField(max_length=1536),
        ),
    ]
