# Generated by Django 5.2.5 on 2025-11-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0005_alter_relationship_left_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
