# Generated by Django 5.2.5 on 2025-11-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0008_label_alter_node_entity_entity_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
