import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Send, Loader, Trash2, FileText, ArrowRight, X } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import PathVisualization from './PathVisualization';
import DocumentViewer from './DocumentViewer';
import NodeGraphModal from './NodeGraphModal';
import { chatKG, clearChatSession, getQuerySuggestions } from '../services/api';

export default function ChatInterface({ onFavoriteClick, isFavorited }) {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [sessionId, setSessionId] = useState(null);
  const [selectedReference, setSelectedReference] = useState(null);
  const [currentReferences, setCurrentReferences] = useState([]);
  const [selectedSegment, setSelectedSegment] = useState(null);
  const [suggestions, setSuggestions] = useState([]);
  const [loadingSuggestions, setLoadingSuggestions] = useState(false);
  const [graphModal, setGraphModal] = useState({ open: false, nodeName: null, relationshipType: null });
  const messagesEndRef = useRef(null);
  const chatContainerRef = useRef(null);

  // Load query suggestions on mount
  useEffect(() => {
    const loadSuggestions = async () => {
      if (messages.length === 0) {
        setLoadingSuggestions(true);
        try {
          const data = await getQuerySuggestions();
          setSuggestions(data.suggestions || []);
        } catch (error) {
          console.error('Failed to load suggestions:', error);
        } finally {
          setLoadingSuggestions(false);
        }
      }
    };
    loadSuggestions();
  }, [messages.length]);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Initialize session ID on mount
  useEffect(() => {
    if (!sessionId) {
      // Session ID will be generated by backend on first message
    }
  }, [sessionId]);

  const handleSend = async (e) => {
    e?.preventDefault?.();
    if (!input.trim() || loading) return;

    const userMessage = input.trim();
    setInput('');
    setLoading(true);
    setCurrentReferences([]);
    setSelectedSegment(null);

    // Add user message to chat
    const newUserMessage = {
      id: Date.now(),
      role: 'user',
      content: userMessage,
      timestamp: new Date()
    };
    setMessages(prev => [...prev, newUserMessage]);

    try {
      const response = await chatKG(userMessage, sessionId);
      
      // Update session ID if this is the first message
      if (!sessionId && response.session_id) {
        setSessionId(response.session_id);
      }

      // Add assistant response
      const assistantMessage = {
        id: Date.now() + 1,
        role: 'assistant',
        content: response.answer,
        timestamp: new Date(),
        references: response.references || [],
        entities: response.entities || [],
        documentPaths: response.document_paths || {},
        graph: response.graph || {}
      };
      
      // Attach document paths to references for easier access
      if (response.document_paths) {
        console.log('Document paths from API:', response.document_paths);
        console.log('References:', assistantMessage.references);
        assistantMessage.references = assistantMessage.references.map(ref => {
          const path = response.document_paths[ref.title];
          console.log(`Looking for path for "${ref.title}":`, path);
          return {
            ...ref,
            documentPath: path
          };
        });
      }
      
      // Filter references based on answer content - don't show if answer indicates no info
      const answerLower = response.answer.toLowerCase();
      const hasNoInfo = [
        'not available',
        'information is not available',
        'not available in the current knowledge base',
        'not available in the knowledge base',
        'cannot be answered',
        'no information',
        'does not contain'
      ].some(phrase => answerLower.includes(phrase));
      
      if (hasNoInfo) {
        assistantMessage.references = [];
      }
      
      setMessages(prev => [...prev, assistantMessage]);
      setCurrentReferences(assistantMessage.references);
    } catch (error) {
      const errorMessage = {
        id: Date.now() + 1,
        role: 'assistant',
        content: `Error: ${error.message}`,
        timestamp: new Date(),
        isError: true
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setLoading(false);
    }
  };

  const handleClearChat = async () => {
    if (sessionId) {
      try {
        await clearChatSession(sessionId);
      } catch (error) {
        console.error('Failed to clear session:', error);
      }
    }
    setMessages([]);
    setSessionId(null);
    setCurrentReferences([]);
    setSelectedSegment(null);
    setSuggestions([]); // Reload suggestions when clearing chat
  };

  const handleReferenceClick = (reference, segment = null) => {
    setSelectedReference(reference);
    setSelectedSegment(segment);
  };

  const handleSuggestionClick = async (suggestion) => {
    if (loading) return;
    
    setInput('');
    setLoading(true);
    setCurrentReferences([]);
    setSelectedSegment(null);

    // Add user message to chat
    const newUserMessage = {
      id: Date.now(),
      role: 'user',
      content: suggestion,
      timestamp: new Date()
    };
    setMessages(prev => [...prev, newUserMessage]);

    try {
      const response = await chatKG(suggestion, sessionId);
      
      // Update session ID if this is the first message
      if (!sessionId && response.session_id) {
        setSessionId(response.session_id);
      }

      // Add assistant response
      const assistantMessage = {
        id: Date.now() + 1,
        role: 'assistant',
        content: response.answer,
        timestamp: new Date(),
        references: response.references || [],
        entities: response.entities || [],
        documentPaths: response.document_paths || {},
        graph: response.graph || {}
      };
      
      // Attach document paths to references for easier access
      if (response.document_paths) {
        console.log('Document paths from API:', response.document_paths);
        console.log('References:', assistantMessage.references);
        assistantMessage.references = assistantMessage.references.map(ref => {
          const path = response.document_paths[ref.title];
          console.log(`Looking for path for "${ref.title}":`, path);
          return {
            ...ref,
            documentPath: path
          };
        });
      }
      
      // Filter references based on answer content - don't show if answer indicates no info
      const answerLower = response.answer.toLowerCase();
      const hasNoInfo = [
        'not available',
        'information is not available',
        'not available in the current knowledge base',
        'not available in the knowledge base',
        'cannot be answered',
        'no information',
        'does not contain'
      ].some(phrase => answerLower.includes(phrase));
      
      if (hasNoInfo) {
        assistantMessage.references = [];
      }
      
      setMessages(prev => [...prev, assistantMessage]);
      setCurrentReferences(assistantMessage.references);
    } catch (error) {
      const errorMessage = {
        id: Date.now() + 1,
        role: 'assistant',
        content: `Error: ${error.message}`,
        timestamp: new Date(),
        isError: true
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex h-[calc(100vh-120px)] gap-4">
      {/* Left: Chat Window */}
      <div className="flex-1 flex flex-col bg-white rounded-lg shadow-sm border border-einstein-gray-200 overflow-hidden">
        {/* Chat Header */}
        <div className="p-5 bg-einstein-blue-light border-b border-einstein-gray-200 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-einstein-gray-800">Chat</h2>
          {messages.length > 0 && (
            <button
              onClick={handleClearChat}
              className="text-sm text-einstein-gray-600 hover:text-red-600 flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-red-50 transition-colors font-medium"
            >
              <Trash2 className="h-4 w-4" />
              Clear Chat
            </button>
          )}
        </div>

        {/* Messages Area */}
        <div ref={chatContainerRef} className="flex-1 overflow-y-auto p-4 space-y-4">
          {messages.length === 0 && (
            <div className="text-center py-8">
              <div className="inline-block p-5 bg-einstein-gray-50 rounded-full mb-5">
                <FileText className="h-10 w-10 text-einstein-gray-400" />
              </div>
              <p className="text-lg font-semibold text-einstein-gray-700 mb-2">Start a conversation</p>
              <p className="text-sm text-einstein-gray-500 mb-6">Ask questions about laboratory procedures and SOPs</p>
              
              {/* Query Suggestions */}
              {suggestions.length > 0 && (
                <div className="mt-8 max-w-2xl mx-auto">
                  <p className="text-sm font-medium text-einstein-gray-600 mb-4">Try asking:</p>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    {suggestions.slice(0, 8).map((suggestion, index) => (
                      <motion.button
                        key={index}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.05 }}
                        onClick={() => handleSuggestionClick(suggestion)}
                        className="text-left p-3 bg-white border border-einstein-gray-200 rounded-md hover:border-einstein-blue hover:bg-einstein-blue-light transition-all text-sm text-einstein-gray-700 hover:text-einstein-blue-dark group"
                      >
                        <span className="group-hover:font-medium">{suggestion}</span>
                      </motion.button>
                    ))}
                  </div>
                </div>
              )}
              {loadingSuggestions && (
                <p className="text-xs text-einstein-gray-500 mt-4">Loading suggestions...</p>
              )}
            </div>
          )}

          <AnimatePresence>
            {messages.map((message) => (
              <motion.div
                key={message.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                <div
                  className={`max-w-[80%] rounded-lg p-4 ${
                    message.role === 'user'
                      ? 'bg-einstein-blue text-white shadow-sm'
                      : message.isError
                      ? 'bg-red-50 text-red-700 border border-red-200'
                      : 'bg-einstein-gray-50 text-einstein-gray-800 border border-einstein-gray-200'
                  }`}
                >
                  {message.role === 'user' ? (
                    <p className="whitespace-pre-wrap">{message.content}</p>
                  ) : (
                    <div>
                      <div className="prose prose-sm max-w-none prose-headings:text-gray-900 prose-headings:font-bold prose-a:text-blue-600 prose-a:underline prose-code:bg-gray-100 prose-code:text-gray-900 prose-code:px-2 prose-code:py-1 prose-code:rounded">
                        <ReactMarkdown
                          remarkPlugins={[remarkGfm]}
                          components={{
                            p: ({node, ...props}) => {
                              const text = props.children?.[0] || '';
                              // Check if this paragraph contains any reference segments
                              const relevantRefs = message.references?.filter(ref => 
                                ref.segments?.some(seg => text.includes(seg.text.substring(0, 50)))
                              ) || [];
                              
                              if (relevantRefs.length > 0) {
                                return (
                                  <p className="text-gray-700 leading-relaxed mb-3 relative group">
                                    {text}
                                    <span className="ml-2 inline-flex items-center gap-1 text-xs text-blue-600 opacity-0 group-hover:opacity-100 transition-opacity">
                                      <FileText className="h-3 w-3" />
                                      {relevantRefs.length} ref{relevantRefs.length > 1 ? 's' : ''}
                                    </span>
                                  </p>
                                );
                              }
                              return <p className="text-gray-700 leading-relaxed mb-3" {...props} />;
                            },
                            table: ({node, ...props}) => <table className="w-full border-collapse mb-4 mt-4 shadow-sm" {...props} />,
                            thead: ({node, ...props}) => <thead className="bg-gray-100 border-b-2 border-gray-300" {...props} />,
                            tbody: ({node, ...props}) => <tbody className="bg-white" {...props} />,
                            tr: ({node, ...props}) => <tr className="border-b border-gray-200 hover:bg-gray-50" {...props} />,
                            th: ({node, ...props}) => <th className="border border-gray-300 px-4 py-2 text-left font-semibold text-gray-900" {...props} />,
                            td: ({node, ...props}) => <td className="border border-gray-300 px-4 py-2 text-gray-700" {...props} />,
                          }}
                        >
                          {message.content}
                        </ReactMarkdown>
                      </div>
                      
                      {message.references && message.references.length > 0 && (
                        <div className="mt-3 pt-3 border-t border-gray-300">
                          <p className="text-xs text-gray-600 mb-2">
                            {message.references.length} reference{message.references.length > 1 ? 's' : ''} available
                          </p>
                        </div>
                      )}
                    </div>
                  )}
                  <p className="text-xs mt-2 opacity-70">
                    {message.timestamp.toLocaleTimeString()}
                  </p>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>

          {loading && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex justify-start"
            >
              <div className="bg-einstein-gray-50 rounded-lg p-4 border border-einstein-gray-200">
                <div className="flex items-center gap-2">
                  <Loader className="h-4 w-4 animate-spin text-einstein-blue" />
                  <span className="text-sm text-einstein-gray-600 font-medium">Thinking...</span>
                </div>
              </div>
            </motion.div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <form onSubmit={handleSend} className="p-5 border-t border-einstein-gray-200 bg-white">
          <div className="flex gap-3">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask a question about laboratory procedures..."
              className="flex-1 px-4 py-3 border border-einstein-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-einstein-blue focus:border-einstein-blue transition-all text-einstein-gray-800 placeholder-einstein-gray-400"
              disabled={loading}
            />
            <button
              type="submit"
              disabled={!input.trim() || loading}
              className="px-6 py-3 bg-einstein-blue text-white rounded-md hover:bg-einstein-blue-dark disabled:bg-einstein-gray-300 disabled:cursor-not-allowed transition-colors flex items-center gap-2 font-medium shadow-sm"
            >
              <Send className="h-4 w-4" />
              Send
            </button>
          </div>
        </form>
      </div>

      {/* Right: References Panel */}
      <div className="w-96 flex flex-col bg-white rounded-lg shadow-sm border border-einstein-gray-200 overflow-hidden">
        <div className="p-5 bg-einstein-green-light border-b border-einstein-gray-200">
          <h2 className="text-lg font-semibold text-einstein-gray-800 flex items-center gap-2">
            <FileText className="h-5 w-5 text-einstein-green" />
            References
            {currentReferences.length > 0 && (
              <span className="text-sm font-normal text-einstein-gray-600">
                ({currentReferences.length})
              </span>
            )}
          </h2>
        </div>

        <div className="flex-1 overflow-y-auto p-4">
          {currentReferences.length === 0 ? (
            <div className="text-center py-16 text-einstein-gray-500">
              <FileText className="h-10 w-10 text-einstein-gray-400 mx-auto mb-3" />
              <p className="text-sm font-medium text-einstein-gray-600 mb-1">No references yet</p>
              <p className="text-xs text-einstein-gray-500">References will appear here when you ask questions</p>
            </div>
          ) : (
            <div className="space-y-4">
              {currentReferences.map((ref, index) => {
                // Use documentPath from reference if available, otherwise try to get from message
                const path = ref.documentPath || 
                  (messages.filter(m => m.documentPaths).pop()?.documentPaths?.[ref.title]);
                
                return (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="bg-einstein-gray-50 rounded-lg p-4 border border-einstein-gray-200 hover:border-einstein-blue hover:shadow-sm transition-all"
                  >
                    {/* Title */}
                    <h4 className="font-semibold text-sm text-einstein-gray-800 mb-2">{ref.title}</h4>

                    {/* Graph Path Visualization */}
                    {path ? (
                      <PathVisualization 
                        path={path}
                        onNodeClick={(nodeName) => {
                          setGraphModal({ open: true, nodeName, relationshipType: null });
                        }}
                        onRelationshipClick={(relType, sourceNode, targetNode) => {
                          // For relationship, show graph centered on source node filtered by relationship type
                          setGraphModal({ open: true, nodeName: sourceNode, relationshipType: relType });
                        }}
                      />
                    ) : (
                      <div className="mt-3 p-3 bg-einstein-gray-100 rounded-md border border-einstein-gray-200">
                        <p className="text-xs text-einstein-gray-600 italic">
                          Graph path information not available
                        </p>
                      </div>
                    )}

                    {/* Segments */}
                    {ref.segments && ref.segments.length > 0 && (
                      <div className="mt-3 space-y-2">
                        <p className="text-xs font-medium text-einstein-gray-600 uppercase tracking-wide mb-2">
                          Related Segments ({ref.segments.length})
                        </p>
                        {ref.segments.map((segment, segIdx) => (
                          <button
                            key={segIdx}
                            onClick={() => handleReferenceClick(ref, segment)}
                            className="w-full text-left p-3 bg-white rounded-md border border-einstein-gray-200 hover:border-einstein-blue hover:bg-einstein-blue-light transition-colors text-xs text-einstein-gray-700 group mb-2"
                          >
                            <p className="line-clamp-2 group-hover:text-einstein-blue-dark font-medium">{segment.text}</p>
                            <span className="text-xs text-einstein-gray-500 mt-1.5 block">Click to view document</span>
                          </button>
                        ))}
                      </div>
                    )}

                    {/* Actions */}
                    <div className="flex gap-2 mt-4">
                      <button
                        onClick={() => handleReferenceClick(ref)}
                        className="flex-1 text-xs px-3 py-2 bg-einstein-blue-light text-einstein-blue hover:bg-einstein-blue hover:text-white rounded-md transition-colors font-medium flex items-center justify-center gap-1.5"
                      >
                        <ArrowRight className="h-3 w-3" />
                        View
                      </button>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Document Viewer Modal */}
      <AnimatePresence>
        {selectedReference && (
          <DocumentViewer
            document={selectedReference}
            segment={selectedSegment}
            onClose={() => {
              setSelectedReference(null);
              setSelectedSegment(null);
            }}
          />
        )}
      </AnimatePresence>

      {/* Graph Modal */}
      {graphModal.open && (
        <NodeGraphModal
          nodeName={graphModal.nodeName}
          relationshipType={graphModal.relationshipType}
          onClose={() => setGraphModal({ open: false, nodeName: null, relationshipType: null })}
        />
      )}
    </div>
  );
}

