# Generated by Django 5.2.5 on 2025-11-07 21:45

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Labels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("marker_markdown_plain", models.TextField()),
                (
                    "marker_markdown_chunks_plain",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "mineru_markdown",
                    models.TextField(
                        blank=True,
                        help_text="The markdown content of the document as generated by mineru.",
                        null=True,
                    ),
                ),
                (
                    "mineru_json_content",
                    models.JSONField(
                        blank=True,
                        help_text="The json content of the document as generated by mineru.",
                        null=True,
                    ),
                ),
                (
                    "nougat_markdown",
                    models.TextField(
                        blank=True,
                        help_text="The markdown content of the document as generated by nougat.",
                        null=True,
                    ),
                ),
                ("table_of_contents", models.JSONField()),
                ("page_stats", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("num_pages", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOP", "sop"),
                            ("FDA/Cardiovascular", "cardiovascular"),
                            ("FDA/Clinical Chemistry", "clinical_chemistry"),
                            ("FDA/Hematology", "hematology"),
                            ("FDA/Immunology", "immunology"),
                            ("FDA/Microbiology", "microbiology"),
                            ("FDA/Molecular Genetics", "molecular_genetics"),
                            ("FDA/Obstetrics/Gynecology", "obstetrics_gynecology"),
                            ("FDA/Pathology", "pathology"),
                            ("FDA/Toxicology", "toxicology"),
                        ],
                        help_text="The category of the document, defined by the folder from the source data.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fda_review_letter",
                    models.ForeignKey(
                        blank=True,
                        help_text="The FDA review letter that this document is a response to, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("text_length", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_metadata", models.JSONField()),
                ("bbox", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                ("page_idx", models.IntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Mineru provides extracted images which can be used for VLM work, but alternatively we can extract an image by bounding box for any chunk.",
                        null=True,
                        upload_to="chunks/",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Caption", "Caption"),
                            ("Code", "Code"),
                            ("Equation", "Equation"),
                            ("Figure", "Figure"),
                            ("FigureGroup", "FigureGroup"),
                            ("Footnote", "Footnote"),
                            ("Form", "Form"),
                            ("Handwriting", "Handwriting"),
                            ("ListGroup", "ListGroup"),
                            ("PageFooter", "PageFooter"),
                            ("PageHeader", "PageHeader"),
                            ("Picture", "Picture"),
                            ("PictureGroup", "PictureGroup"),
                            ("SectionHeader", "SectionHeader"),
                            ("Table", "Table"),
                            ("TableGroup", "TableGroup"),
                            ("TableOfContents", "TableOfContents"),
                            ("Text", "Text"),
                            ("TextInlineMath", "TextInlineMath"),
                            ("MarkdownKVTable", "MarkdownKVTable"),
                        ],
                        help_text="The type of block this chunk is, e.g. 'table', 'header', etc. This information is extracted from the page_metadata.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                ("entities_parsed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entities_parse_failed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "entities_parse_failed_message",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "relationships_parsed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "relationships_parse_failed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "relationships_parse_failed_message",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "parent_chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.chunk",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.document"
                    ),
                ),
            ],
        ),
    ]
