# Generated by Django 5.2.5 on 2025-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="block_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Caption", "Caption"),
                    ("Code", "Code"),
                    ("Equation", "Equation"),
                    ("Figure", "Figure"),
                    ("FigureGroup", "FigureGroup"),
                    ("Footnote", "Footnote"),
                    ("Form", "Form"),
                    ("Handwriting", "Handwriting"),
                    ("ListGroup", "ListGroup"),
                    ("PageFooter", "PageFooter"),
                    ("PageHeader", "PageHeader"),
                    ("Picture", "Picture"),
                    ("PictureGroup", "PictureGroup"),
                    ("SectionHeader", "SectionHeader"),
                    ("Table", "Table"),
                    ("TableGroup", "TableGroup"),
                    ("TableOfContents", "TableOfContents"),
                    ("Text", "Text"),
                    ("TextInlineMath", "TextInlineMath"),
                    ("MarkdownKVTable", "MarkdownKVTable"),
                    ("VisionTable", "VisionTable"),
                ],
                help_text="The type of block this chunk is, e.g. 'table', 'header', etc. This information is extracted from the page_metadata.",
                max_length=255,
                null=True,
            ),
        ),
    ]
