# Generated by Django 5.2.5 on 2025-09-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='markdown_chunks_openai',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
