# Generated by Django 5.2.5 on 2025-11-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_chunk_block_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chunk",
            name="entities_parse_failed_at",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="entities_parse_failed_message",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="entities_parsed_at",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="relationships_parse_failed_at",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="relationships_parse_failed_message",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="relationships_parsed_at",
        ),
    ]
