# Generated by Django 5.2.5 on 2025-09-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_markdown_chunks_openai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='markdown_chunks_openai',
        ),
    ]
