# Generated by Django 5.2.5 on 2025-11-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_chunk_entities_parse_failed_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Labels",
        ),
    ]
