# Generated by Django 5.2.5 on 2025-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_document_markdown_chunks_openai'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='markdown_chunks_openai',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
