# Generated by Django 5.2.5 on 2025-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_document_markdown_chunks_openai'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='bbox',
            field=models.JSONField(default='[0,0,0,0]'),
            preserve_default=False,
        ),
    ]
