# Generated by Django 5.2.5 on 2025-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_chunk_embedding_alter_chunk_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
