# Generated by Django 5.2.5 on 2025-10-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0010_rename_markdown_chunks_openai_document_marker_markdown_chunks_plain",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="entities_parse_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chunk",
            name="entities_parse_failed_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chunk",
            name="entities_parsed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chunk",
            name="relationships_parse_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chunk",
            name="relationships_parse_failed_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chunk",
            name="relationships_parsed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="marker_markdown_chunks_plain",
            field=models.JSONField(
                blank=True,
                help_text="The chunks generated by marker-pdf using basic settings.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="marker_markdown_plain",
            field=models.TextField(
                help_text="The plain text content of the document as generated by marker-pdf using basic settings (no LLM, etc.)"
            ),
        ),
    ]
