# Generated by Django 5.2.5 on 2025-11-02 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_chunk_entities_parse_failed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chunk",
            name="parent_chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.chunk",
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="block_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Caption", "Caption"),
                    ("Code", "Code"),
                    ("Equation", "Equation"),
                    ("Figure", "Figure"),
                    ("FigureGroup", "FigureGroup"),
                    ("Footnote", "Footnote"),
                    ("Form", "Form"),
                    ("Handwriting", "Handwriting"),
                    ("ListGroup", "ListGroup"),
                    ("PageFooter", "PageFooter"),
                    ("PageHeader", "PageHeader"),
                    ("Picture", "Picture"),
                    ("PictureGroup", "PictureGroup"),
                    ("SectionHeader", "SectionHeader"),
                    ("Table", "Table"),
                    ("TableGroup", "TableGroup"),
                    ("TableOfContents", "TableOfContents"),
                    ("Text", "Text"),
                    ("TextInlineMath", "TextInlineMath"),
                    ("MarkdownKVTable", "MarkdownKVTable"),
                ],
                help_text="The type of block this chunk is, e.g. 'table', 'header', etc. This information is extracted from the page_metadata.",
                max_length=255,
                null=True,
            ),
        ),
    ]
