# Generated by Django 5.2.5 on 2025-11-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_chunk_is_active_chunk_parent_chunk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="mineru_json_content",
            field=models.JSONField(
                blank=True,
                help_text="The json content of the document as generated by mineru.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="mineru_markdown",
            field=models.TextField(
                blank=True,
                help_text="The markdown content of the document as generated by mineru.",
                null=True,
            ),
        ),
    ]
