# Generated by Django 5.2.5 on 2025-11-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_document_mineru_json_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="page_idx",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
