# Generated by Django 5.2.5 on 2025-11-02 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_chunk_page_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Mineru provides extracted images which can be used for VLM work, but alternatively we can extract an image by bounding box for any chunk.",
                null=True,
                upload_to="chunks/",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOP", "sop"),
                    ("FDA/Cardiovascular", "cardiovascular"),
                    ("FDA/Clinical Chemistry", "clinical_chemistry"),
                    ("FDA/Hematology", "hematology"),
                    ("FDA/Immunology", "immunology"),
                    ("FDA/Microbiology", "microbiology"),
                    ("FDA/Molecular Genetics", "molecular_genetics"),
                    ("FDA/Obstetrics/Gynecology", "obstetrics_gynecology"),
                    ("FDA/Pathology", "pathology"),
                    ("FDA/Toxicology", "toxicology"),
                ],
                help_text="The category of the document, defined by the folder from the source data.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="fda_review_letter",
            field=models.ForeignKey(
                blank=True,
                help_text="The FDA review letter that this document is a response to, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="nougat_markdown",
            field=models.TextField(
                blank=True,
                help_text="The markdown content of the document as generated by nougat.",
                null=True,
            ),
        ),
    ]
